#!/usr/bin/env python3
"""Build and verify an anonymous TMLR supplementary ZIP.

The source repository is intentionally public and contains named publication
links. This builder starts from the curated public release profile, replaces
identity-bearing strings and filenames, removes generated bytecode, verifies
the figure layer again, fails closed on remaining identity markers, and writes
a deterministic ZIP plus SHA-256 sidecar.
"""

from __future__ import annotations

import argparse
import hashlib
import re
import shutil
import subprocess
import sys
import tempfile
import zipfile
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[3]
BUILD_PUBLIC = REPO_ROOT / "journal" / "writeup" / "scripts" / "build_release_package.py"
DEFAULT_OUTPUT = Path("/tmp/toy-models-sft-anonymous-supplement.zip")
ARCHIVE_ROOT = "toy-models-sft-anonymous-supplement"

TEXT_REPLACEMENTS = (
    ("Anton de la Fuente", "Anonymous author"),
    ("anton de la fuente", "anonymous author"),
    ("antondelafuente.com", "project-site-withheld.invalid"),
    ("antondelafuente", "anonymous-author"),
    ("matonski", "anonymous-author"),
    ("/home/anton", "<private-workspace>"),
    ("Arthur Conmy", "Anonymous coauthor"),
    ("arthur conmy", "anonymous coauthor"),
    ("Arthur", "coauthor"),
    ("arthur", "coauthor"),
    ("Anton's", "the author's"),
    ("Anton", "the author"),
    ("~/MATS", "<private-workspace>"),
)

# Regex replacements run after the plain-string pass. Word-boundary anchored
# so e.g. "FORMATS" is untouched. These scrub research-program markers that
# narrow the author pool under double-blind review, not just literal names.
REGEX_REPLACEMENTS = (
    (re.compile(r"\bMATS\b"), "lab"),
    (re.compile(r"\bNeel\b"), "offsite"),
)

# These are checked case-insensitively in every path and every file's raw
# bytes after replacements. Keep the list narrow enough to avoid false hits
# such as "constant" while covering the actual author identifiers.
FORBIDDEN_MARKERS = (
    "anton de la fuente",
    "antondelafuente",
    "matonski",
    "/home/anton",
    "arthur conmy",
    "gmail.com",
)

FROZEN_DATA_PREFIXES = (
    "training_data/",
    "eval_outputs/",
    "journal/writeup/methods/toy/self_preservation/petri_behavior/",
    "registry/reasons-filler-control/analysis/results/",
)

# Regex forbidden markers, checked against decoded text of every text file
# and every path (the byte scan above cannot do word boundaries).
REGEX_FORBIDDEN = (
    re.compile(r"\bMATS\b"),
    re.compile(r"\bneel\b", re.IGNORECASE),
)

TEXT_SUFFIXES = {
    ".css",
    ".csv",
    ".html",
    ".js",
    ".json",
    ".jsonl",
    ".md",
    ".mjs",
    ".py",
    ".svg",
    ".tex",
    ".ts",
    ".tsx",
    ".txt",
    ".yaml",
    ".yml",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    return parser.parse_args()


def run(cmd: list[str], cwd: Path) -> None:
    print("+ " + " ".join(cmd))
    subprocess.run(cmd, cwd=cwd, check=True)


def remove_generated_bytecode(root: Path) -> None:
    for path in sorted(root.rglob("__pycache__"), reverse=True):
        shutil.rmtree(path)
    for path in root.rglob("*.pyc"):
        path.unlink()


def anonymized_name(name: str) -> str:
    out = name
    for old, new in TEXT_REPLACEMENTS:
        out = out.replace(old, new)
    return out


def rename_identity_paths(root: Path) -> None:
    paths = sorted(root.rglob("*"), key=lambda p: len(p.parts), reverse=True)
    for path in paths:
        new_name = anonymized_name(path.name)
        if new_name != path.name:
            path.rename(path.with_name(new_name))


def is_text_file(path: Path) -> bool:
    return path.suffix.lower() in TEXT_SUFFIXES or path.name in {"README", "LICENSE"}


def anonymize_text_files(root: Path) -> None:
    for path in sorted(p for p in root.rglob("*") if p.is_file() and is_text_file(p)):
        rel = path.relative_to(root).as_posix()
        # Frozen research records must remain byte-identical to their published
        # checksums. Strong author identifiers are still scanned below; common
        # benchmark text such as example Gmail addresses is not author metadata.
        if rel.startswith(FROZEN_DATA_PREFIXES):
            continue
        text = path.read_text(encoding="utf-8")
        for old, new in TEXT_REPLACEMENTS:
            text = text.replace(old, new)
        for pattern, new in REGEX_REPLACEMENTS:
            text = pattern.sub(new, text)
        path.write_text(text, encoding="utf-8")


def normalize_generated_metadata(root: Path) -> None:
    for path in sorted(p for p in root.rglob("*") if p.is_file() and is_text_file(p)):
        rel = path.relative_to(root).as_posix()
        if rel.startswith(FROZEN_DATA_PREFIXES):
            continue
        text = path.read_text(encoding="utf-8")
        text = re.sub(r"(?m)^Generated: .+$", "Generated: omitted for anonymous review", text)
        text = re.sub(
            r'"generated_at_utc"\s*:\s*"[^"]+"',
            '"generated_at_utc": "omitted-for-anonymous-review"',
            text,
        )
        path.write_text(text, encoding="utf-8")


def write_anonymous_readme(root: Path) -> None:
    readme = root / "README.md"
    existing = readme.read_text(encoding="utf-8")
    notice = """# Anonymous supplementary material

This ZIP accompanies an anonymous manuscript. Author names and named project
URLs have been removed. It contains the frozen figure layer, complete toy-method
source, checksum-pinned toy training and evaluation inputs, row-level toy claim
traces, compact experiment records, and provenance needed to trace the paper's
reported values. Model weights and raw agentic-misalignment evaluation
artifacts are not included in the review package.

The source repository and named artifact locations will be disclosed after the
double-blind review period.

"""
    readme.write_text(notice + existing, encoding="utf-8")


def scan_forbidden(root: Path) -> list[str]:
    findings: list[str] = []
    for path in sorted(root.rglob("*")):
        rel = path.relative_to(root).as_posix()
        rel_lower = rel.lower()
        frozen_data = rel.startswith(FROZEN_DATA_PREFIXES)
        markers = FORBIDDEN_MARKERS[:-1] if frozen_data else FORBIDDEN_MARKERS
        for marker in markers:
            if marker in rel_lower:
                findings.append(f"path:{rel}:{marker}")
        if not frozen_data:
            for pattern in REGEX_FORBIDDEN:
                if pattern.search(rel):
                    findings.append(f"path:{rel}:{pattern.pattern}")
        if not path.is_file():
            continue
        data = path.read_bytes().lower()
        for marker in markers:
            if marker.encode() in data:
                findings.append(f"content:{rel}:{marker}")
        if is_text_file(path) and not frozen_data:
            text = path.read_text(encoding="utf-8", errors="ignore")
            for pattern in REGEX_FORBIDDEN:
                if pattern.search(text):
                    findings.append(f"content:{rel}:{pattern.pattern}")
    return findings


def verify_required_records(root: Path) -> None:
    required = (
        "replay-onmodel-crux",
        "teacher-dependence",
        "reasons-filler-control",
        "reasons-filler-inert",
        "conditional-boxing-prefill",
        "toy-reason-beyond-redo",
        "midtrain-pareto",
        "gpqa-2x2-shared-base",
    )
    missing = [name for name in required if not (root / "registry" / name / "RESULTS.md").is_file()]
    if missing:
        raise RuntimeError(f"missing paper-cited result records: {missing}")


def make_zip(root: Path, output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    if output.exists():
        output.unlink()
    with zipfile.ZipFile(output, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for path in sorted(p for p in root.rglob("*") if p.is_file()):
            rel = Path(ARCHIVE_ROOT) / path.relative_to(root)
            info = zipfile.ZipInfo(rel.as_posix(), date_time=(1980, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = (0o100644 & 0xFFFF) << 16
            archive.writestr(info, path.read_bytes())


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def main() -> None:
    args = parse_args()
    output = args.output.resolve()
    with tempfile.TemporaryDirectory(prefix="toy-models-sft-anon-") as temp:
        package = Path(temp) / "package"
        run(
            [
                sys.executable,
                str(BUILD_PUBLIC),
                "--output",
                str(package),
                "--profile",
                "public",
                "--clean",
            ],
            REPO_ROOT,
        )
        remove_generated_bytecode(package)
        rename_identity_paths(package)
        anonymize_text_files(package)
        normalize_generated_metadata(package)
        write_anonymous_readme(package)
        verify_required_records(package)

        run(
            [sys.executable, "journal/writeup/scripts/rebuild_all_figures.py", "--skip-source-check"],
            package,
        )
        run([sys.executable, "journal/writeup/methods/toy/verify_frozen_data.py"], package)
        run([sys.executable, "journal/writeup/methods/toy/recompute_toy_claims.py"], package)
        remove_generated_bytecode(package)

        findings = scan_forbidden(package)
        if findings:
            raise RuntimeError("anonymous supplement leak scan failed:\n" + "\n".join(findings))

        make_zip(package, output)

    checksum = sha256(output)
    checksum_path = output.with_suffix(output.suffix + ".sha256")
    checksum_path.write_text(f"{checksum}  {output.name}\n", encoding="utf-8")
    print(f"wrote {output}")
    print(f"sha256 {checksum}")
    print(f"bytes {output.stat().st_size}")


if __name__ == "__main__":
    main()
